# Generated by Django 2.0.6 on 2018-07-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(max_length=50, null=True)),
                ('country', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='diseaseinstance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.DiseaseType'),
        ),
    ]
