# Generated by Django 2.0.6 on 2018-08-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20180702_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('region', models.CharField(max_length=5)),
                ('country', models.CharField(max_length=5)),
                ('display', models.CharField(blank=True, max_length=50)),
                ('numeric', models.IntegerField(blank=True)),
                ('low', models.IntegerField(blank=True)),
                ('high', models.IntegerField(blank=True)),
            ],
        ),
    ]
