# Generated by Django 2.0.6 on 2018-08-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='display',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='high',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='low',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='numeric',
            field=models.IntegerField(null=True),
        ),
    ]
