# Generated by Django 2.0.6 on 2018-08-09 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20180809_0002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
