# Generated by Django 2.0.6 on 2018-08-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='country',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='region',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
