# Generated by Django 2.0.6 on 2018-08-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20180809_0151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
    ]
