# Generated by Django 2.0.6 on 2018-08-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='display',
        ),
    ]
