# Generated by Django 2.0.6 on 2018-08-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20180809_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
