# Generated by Django 2.0.6 on 2018-08-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_auto_20180809_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
