# Generated by Django 2.0.6 on 2018-08-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_auto_20180809_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='high',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='low',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='numeric',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
