# Generated by Django 2.0.6 on 2018-08-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_auto_20180809_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='year',
            field=models.FloatField(null=True),
        ),
    ]
