# Generated by Django 2.0.6 on 2018-08-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_auto_20180815_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='high',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='low',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='numeric',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
